# Generated by Django 4.2.7 on 2025-06-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
