# Generated by Django 4.2.7 on 2025-06-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0003_horariocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='smapp.asignatura'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='smapp.estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='smapp.profesor'),
        ),
    ]
