# Generated by Django 4.2.7 on 2025-06-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0004_curso_asignaturas_curso_estudiantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='profesor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='smapp.profesor'),
        ),
    ]
