# Generated by Django 4.2.7 on 2025-06-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0008_profesor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariocurso',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='smapp.asignatura'),
        ),
    ]
