# Generated by Django 4.2.7 on 2025-06-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0009_horariocurso_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
