# Generated by Django 4.2.7 on 2025-06-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0010_calificacion_descripcion_calificacion_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='smapp.asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable', to='smapp.profesor'),
        ),
    ]
