# Generated by Django 4.2.7 on 2025-06-23 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0011_profesor_asignaturas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'asignatura', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smapp.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura', 'fecha')},
            },
        ),
    ]
