# Generated by Django 4.2.7 on 2025-06-23 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0012_asistenciaprofesor_asistenciaalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.asignatura'),
        ),
    ]
