# Generated by Django 4.2.7 on 2025-06-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0013_alter_asistenciaprofesor_asignatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['anio', 'nivel', 'paralelo']},
        ),
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(default=2025, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('1', '1° Medio'), ('2', '2° Medio'), ('3', '3° Medio'), ('4', '4° Medio')], default='1', max_length=1, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='curso',
            name='paralelo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1, verbose_name='Paralelo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_jefatura', to='smapp.profesor', verbose_name='Profesor Jefe'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_documento',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='numero_documento',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nivel', 'paralelo', 'anio')},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='codigo_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor_responsable',
        ),
    ]
