# Generated by Django 4.2.7 on 2025-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0014_alter_curso_options_curso_anio_curso_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('1B', '1° Básico'), ('2B', '2° Básico'), ('3B', '3° Básico'), ('4B', '4° Básico'), ('5B', '5° Básico'), ('6B', '6° Básico'), ('7B', '7° Básico'), ('8B', '8° Básico'), ('1M', '1° Medio'), ('2M', '2° Medio'), ('3M', '3° Medio'), ('4M', '4° Medio')], default='1M', max_length=2, verbose_name='Nivel'),
        ),
    ]
