# Generated by Django 4.2.7 on 2025-06-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0015_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(default=2025, editable=False, verbose_name='Año'),
        ),
    ]
