# Generated by Django 4.2.7 on 2025-06-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0016_alter_curso_anio'),
    ]

    operations = [
    ]
