# Generated by Django 4.2.7 on 2025-06-27 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smapp', '0017_auto_20250626_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Evento de Calendario', 'verbose_name_plural': 'Eventos de Calendario'},
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='smapp.curso'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='para_todos_los_cursos',
            field=models.BooleanField(default=False, verbose_name='Para todos los cursos'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='tipo_evento',
            field=models.CharField(choices=[('general', 'Evento General'), ('evaluacion', 'Evaluación/Prueba'), ('reunion', 'Reunión'), ('actividad', 'Actividad Escolar'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], default='general', max_length=15),
        ),
    ]
