# Generated by Django 4.2.7 on 2025-06-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0018_alter_eventocalendario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='profesores_responsables',
            field=models.ManyToManyField(blank=True, related_name='asignaturas_responsable', to='smapp.profesor'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor_responsable',
            field=models.ForeignKey(blank=True, help_text='Campo deprecado - usar profesores_responsables', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable_old', to='smapp.profesor'),
        ),
    ]
