# Generated by Django 4.2.7 on 2025-06-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0019_agregar_profesores_responsables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariocurso',
            options={'ordering': ['dia', 'hora_inicio'], 'verbose_name': 'Horario de Curso', 'verbose_name_plural': 'Horarios de Curso'},
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_asignados', to='smapp.profesor'),
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='tipo_periodo',
            field=models.CharField(choices=[('clase', 'Clase'), ('recreo', 'Recreo'), ('almuerzo', 'Almuerzo'), ('otro', 'Otro')], default='clase', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='horariocurso',
            unique_together={('curso', 'dia', 'hora_inicio', 'hora_fin')},
        ),
    ]
