# Generated by Django 4.2.7 on 2025-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0020_alter_horariocurso_options_horariocurso_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numero_documento',
            field=models.CharField(max_length=15, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('RUT', 'RUT (Rol Único Tributario)'), ('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='RUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='numero_documento',
            field=models.CharField(max_length=15, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipo_documento',
            field=models.CharField(choices=[('RUT', 'RUT (Rol Único Tributario)'), ('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='RUT', max_length=3),
        ),
    ]
