# Generated by Django 4.2.7 on 2025-06-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0022_alter_asistenciaalumno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='hora_registro',
            field=models.TimeField(auto_now_add=True, help_text='Hora en que se registró la asistencia'),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='hora_registro',
            field=models.TimeField(auto_now_add=True, help_text='Hora en que se registró la asistencia'),
        ),
    ]
