# Generated by Django 4.2.7 on 2025-06-29 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0023_alter_asistenciaalumno_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha del registro de asistencia'),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='hora_registro',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora en que se registró la asistencia'),
        ),
    ]
