# Generated by Django 4.2.7 on 2025-06-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0025_eventocalendario_solo_profesores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('neutra', 'Neutra')], default='neutra', max_length=10)),
                ('categoria', models.CharField(choices=[('comportamiento', 'Comportamiento'), ('rendimiento', 'Rendimiento Académico'), ('disciplina', 'Disciplina'), ('participacion', 'Participación'), ('puntualidad', 'Puntualidad'), ('responsabilidad', 'Responsabilidad'), ('colaboracion', 'Colaboración'), ('actitud', 'Actitud'), ('otro', 'Otro')], default='comportamiento', max_length=15)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la anotación')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('puntos', models.IntegerField(default=0, help_text='Puntos asignados: positivos para buen comportamiento, negativos para mal comportamiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_grave', models.BooleanField(default=False, verbose_name='Anotación grave')),
                ('requiere_atencion_apoderado', models.BooleanField(default=False, verbose_name='Requiere atención del apoderado')),
                ('comunicado_apoderado', models.BooleanField(default=False, verbose_name='Apoderado comunicado')),
                ('fecha_comunicacion_apoderado', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones', to='smapp.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='smapp.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='smapp.estudiante')),
                ('profesor_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_creadas', to='smapp.profesor')),
            ],
            options={
                'verbose_name': 'Anotación',
                'verbose_name_plural': 'Anotaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
