# Generated by Django 4.2.7 on 2025-06-30 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0026_auto_20250630_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaalumno',
            options={'ordering': ['-fecha', 'estudiante__primer_nombre']},
        ),
        migrations.AlterModelOptions(
            name='asistenciaprofesor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horariocurso',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaalumno',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='horariocurso',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='profesores_responsables',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='hora_registro',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='justificacion',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='registrado_por_usuario',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable', to='smapp.profesor'),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_alumnos', to='smapp.asignatura'),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='curso',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_alumnos', to='smapp.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='smapp.estudiante'),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='hora_registro',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Justificación en caso de ausencia', null=True),
        ),
        migrations.AlterField(
            model_name='asistenciaalumno',
            name='profesor_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_registradas', to='smapp.profesor'),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.asignatura'),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_documento',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='numero_documento',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaalumno',
            unique_together={('estudiante', 'curso', 'asignatura', 'fecha')},
        ),
        migrations.RemoveField(
            model_name='asistenciaalumno',
            name='registrado_por_usuario',
        ),
        migrations.RemoveField(
            model_name='horariocurso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='horariocurso',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='horariocurso',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='horariocurso',
            name='tipo_periodo',
        ),
    ]
