# Generated by Django 4.2.7 on 2025-06-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smapp', '0027_alter_asistenciaalumno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaprofesor',
            options={'ordering': ['-fecha', 'profesor__primer_nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaprofesor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_profesores', to='smapp.curso'),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='hora_registro',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Justificación en caso de ausencia', null=True),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='registrado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_profesores_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_profesores', to='smapp.asignatura'),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='smapp.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaprofesor',
            unique_together={('profesor', 'asignatura', 'curso', 'fecha')},
        ),
    ]
