# Generated by Django 4.2.7 on 2025-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0028_alter_asistenciaprofesor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
