# Generated by Django 4.2.7 on 2025-07-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0029_auto_20250630_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='smapp.estudiante'),
        ),
    ]
