# Generated by Django 4.2.7 on 2025-07-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0032_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='estado_civil',
            field=models.CharField(
                choices=[
                    ('soltero', 'Soltero/a'),
                    ('casado', 'Casado/a'),
                    ('divorciado', 'Divorciado/a'),
                    ('viudo', 'Viudo/a'),
                    ('union_libre', 'Unión Libre'),
                ],
                default='soltero',
                max_length=15
            ),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='contacto_emergencia',
            field=models.CharField(
                blank=True, 
                max_length=200, 
                null=True,
                help_text="Nombre y relación del contacto de emergencia"
            ),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='notas_adicionales',
            field=models.TextField(
                blank=True, 
                null=True,
                help_text="Información adicional sobre el apoderado"
            ),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='profesor',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='apoderado',
                to='smapp.profesor',
                help_text="Profesor asociado si el apoderado también es profesor del colegio"
            ),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='tipo_apoderado',
            field=models.CharField(
                choices=[
                    ('padre', 'Padre'),
                    ('madre', 'Madre'),
                    ('abuelo', 'Abuelo/a'),
                    ('tio', 'Tío/a'),
                    ('hermano', 'Hermano/a'),
                    ('tutor', 'Tutor Legal'),
                    ('profesor', 'Profesor Responsable'),
                    ('otro', 'Otro'),
                ],
                default='padre',
                max_length=15
            ),
        ),
    ]
