# Generated by Django 4.2.7 on 2025-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0034_alter_apoderado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='codigo_apoderado',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
