# Generated by Django 4.2.7 on 2025-07-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0035_alter_apoderado_codigo_apoderado'),
    ]

    operations = [
    ]
