# Generated by Django 4.2.7 on 2025-07-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0036_auto_20250705_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoderadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('titular', 'Apoderado Titular'), ('suplente', 'Apoderado Suplente')], default='titular', max_length=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre la relación apoderado-estudiante', null=True)),
            ],
            options={
                'verbose_name': 'Relación Apoderado-Estudiante',
                'verbose_name_plural': 'Relaciones Apoderado-Estudiante',
                'ordering': ['tipo_relacion', '-fecha_asignacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='apoderado',
            options={'ordering': ['apellido_paterno', 'primer_nombre'], 'verbose_name': 'Apoderado', 'verbose_name_plural': 'Apoderados'},
        ),
        migrations.RenameField(
            model_name='apoderado',
            old_name='ocupacion',
            new_name='profesion',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='codigo_apoderado',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='puede_retirar',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión Libre')], default='soltero', max_length=15),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='notas_adicionales',
            field=models.TextField(blank=True, help_text='Información adicional sobre el apoderado', null=True),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='contacto_emergencia',
            field=models.CharField(blank=True, help_text='Nombre y relación del contacto de emergencia', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='tipo_apoderado',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('tutor', 'Tutor Legal'), ('profesor', 'Profesor Responsable'), ('otro', 'Otro')], default='padre', max_length=15),
        ),
        migrations.DeleteModel(
            name='RelacionApoderadoEstudiante',
        ),
        migrations.AddField(
            model_name='apoderadoestudiante',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_estudiante', to='smapp.apoderado'),
        ),
        migrations.AddField(
            model_name='apoderadoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_apoderado', to='smapp.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='apoderadoestudiante',
            unique_together={('apoderado', 'estudiante', 'tipo_relacion')},
        ),
    ]
