# Generated by Django 4.2.7 on 2025-07-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0040_perfil_cargo_perfil_fecha_ingreso_perfil_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='RUT, Pasaporte o Cédula', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_documento',
            field=models.CharField(choices=[('rut', 'RUT'), ('pasaporte', 'Pasaporte'), ('cedula_extranjera', 'Cédula de Extranjería')], default='rut', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo específico para directores', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso para directores', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('director', 'Director'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], max_length=10),
        ),
    ]
