# Generated by Django 5.2.5 on 2025-11-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0041_perfil_direccion_perfil_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariocurso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='smapp.profesor'),
        ),
    ]
