# Generated by Django 5.2.5 on 2025-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0042_horariocurso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('director', 'Director'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], max_length=50),
        ),
    ]
