# Generated by Django 5.2.5 on 2025-11-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0043_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('director', 'Director'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], max_length=20),
        ),
    ]
