# Generated by Django 5.2.5 on 2025-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0044_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='solo_apoderados',
            field=models.BooleanField(default=False, verbose_name='Solo para apoderados'),
        ),
    ]
